### ISSUE TITLE
Make Point Symbols Larger

### ISSUE THREAD

**Issue by bfreeds** [bfreeds/friendsofcascobay#2]

**Comment by bfreeds** [comment]
@slymanFOCB I made the points a little larger.  Can you take a look and let me know if they're large enough?

We can also change the size of the points based on the level of zoom, so if you notice a certain zoom level that's not sized right let me know and I can make a change.

**Comment by slymanFOCB** [comment]
It seems like they are the same size at each level, is that true? 

I see that they can't be much larger at the zoomed out levels, because they'd overlap. Once I zoom in 3 times though, it would be nice if they were slightly large and therefore easier to click.

**Comment by bfreeds** [comment]
@slymanFOCB It was, I tweaked it a bit- does it look better?  Does the highest zoom level look OK?

**Comment by slymanFOCB** [comment]
Looks great! Nice work!

**Comment by bfreeds** [comment]
Thanks!  I'm going to mark this issue as "closed" ---this means it won't show up as an active issue, and we're saying it's done (we can re-open or create a new one later if we notice something that needs to be changed with the point styling).

For reference, this is the CSS that is styling the points on the map:

``` 
#table_2005_2012_data_sheet1{
  marker-fill-opacity: 0.8;
  marker-line-color: #000000;
  marker-line-width: .5;
  marker-line-opacity: 1;
  marker-width: 12;
  marker-allow-overlap: true;
}
#table_2005_2012_data_sheet1 [zoom>=11]{
  marker-width: 17;
}
#table_2005_2012_data_sheet1 [zoom>=12]{
  marker-width: 20;
}
#table_2005_2012_data_sheet1 [zoom>=14]{
  marker-width: 25;
}
```
